# Generated by Django 2.0.2 on 2021-07-06 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_element', models.CharField(blank=True, max_length=100, null=True)),
                ('data_purchase_number', models.CharField(blank=True, max_length=100, null=True)),
                ('data_doc_publish_date', models.DateField(blank=True, null=True)),
                ('data_purchase_object_info', models.TextField(blank=True, max_length=1000, null=True)),
                ('responsible_org_reg_num', models.CharField(blank=True, max_length=100, null=True)),
                ('responsible_org_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('lot_max_price', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Curator')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
    ]
